app/urls.py
from django.urls import path
from .views import EstoqueCreateView, EstoqueDetailView, EstoqueListView, EstoqueUpdateView, EstoqueDeleteView, home
from app import views

urlpatterns = [
    path('', home, name='home'),
    path('login/', views.login_view, name = "login"),
    path('form_estoque/', EstoqueCreateView.as_view(), name="form_estoque"),  
    path('lista_estoque/', EstoqueListView.as_view(), name="lista_estoque"),  
    path('form_estoque/<int:pk>/', EstoqueUpdateView.as_view(), name="editar_produto"),  
    path('lista_produto/<int:pk>/', EstoqueDetailView.as_view(), name="listar_produto"),  
    path('remover_produto/<int:pk>/', EstoqueDeleteView.as_view(), name="remover_produto"),
]

estoque/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls'))
]

app/models.py
from django.db import models

from django.db import models
class Estoque(models.Model):
    produto = models.CharField(max_length=100, null= False, blank=False)
    data_compra = models.DateField(null=False, blank=False)
    data_vencimento = models.DateField(null=False, blank=False)
    quantidade = models.DecimalField(max_digits=8, decimal_places=2, null=False, blank=False)

app/views.py
from django.contrib import messages
from django.shortcuts import render

from django.views.generic import CreateView
from .models import Estoque
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic import ( CreateView, ListView, UpdateView, DetailView, DeleteView )
from django.urls import reverse_lazy

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()  
            login(request, user)   
            return redirect('lista_estoque')  
        

    else:
        form = AuthenticationForm()

    return render(request, 'login.html', {'form': form})

def home(request):
    return render(request, 'home.html')


class EstoqueCreateView(CreateView):
    model= Estoque
    fields = "__all__"
    template_name = "form_estoque.html"
    success_url = reverse_lazy ("lista_estoque")   

class EstoqueListView(ListView):
    model = Estoque
    template_name = "lista_estoque.html"

class EstoqueUpdateView(UpdateView):
    model = Estoque
    fields = "__all__"
    template_name = "form_estoque.html"
    success_url = reverse_lazy("lista_estoque")
    
class EstoqueDetailView(DetailView):
    model = Estoque  
    template_name = "lista_produto.html" 
    context_object_name = "fun"
    
class EstoqueDeleteView(DeleteView):
    model = Estoque
    template_name = "remover_produto.html"
    success_url = reverse_lazy("lista_estoque")
    

app/templates/form_estoque.html
{% load static %}
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <link rel="stylesheet" href="{% static 'admin/css/estilo.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulário de Estoque</title>
    <link rel="icon" type="image/png" href="{% static 'admin/img/box.png' %}">
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body class="body_principal">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="card shadow-sm border-0">
                <div class="card-body">
                    <h3 class="text-center fw-bold mb-4">Cadastro de Produto</h3>
                    <form method="post" class="fw-bold mb-4 text-dark">
                        {% csrf_token %}
                        
                        <div class="mb-3">
                            <label for="id_produto" class="form-label">Nome do Produto:</label>
                            <input type="text" name="produto" id="produto" class="form-control" required>
                        </div>

                        <div class="mb-3">
                            <label for="id_data_compra" class="form-label">Data de Compra:</label>
                            <input type="date" name="data_compra" id="id_data_compra" class="form-control" required>
                        </div>

                        <div class="mb-3">
                            <label for="id_data_vencimento" class="form-label">Data de Vencimento:</label>
                            <input type="date" name="data_vencimento" id="id_data_vencimento" class="form-control" required>
                        </div>

                        <div class="mb-3">
                            <label for="id_quantidade" class="form-label">Quantidade:</label>
                            <input type="number" step="0.01" name="quantidade" id="id_quantidade" class="form-control" required>
                        </div>

                        <div class="text-center mt-4">
                            <button type="submit" class="btn btn-danger btn-sm px-4">Cadastrar</button>
                            <a href="{% url 'lista_estoque' %}" class="btn btn-info btn-sm px-4">Cancelar</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <hr class="featurette-divider">
    <footer class="rodape">
        <hr class="featurette-divider">
        <div class="container">
            <p class="mb-1">
                &copy; Desenvolvido pelos alunos Felipe e Gabriel &middot;
            </p>
        </div>
    </footer>
</body>
</html>
s

app/templates/home.html
{% load static %}
{% load django_bootstrap5 %}
<!DOCTYPE html> 
<html lang="pt-br">
<head>
    <link rel="stylesheet" href="{% static 'admin/css/estilo.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Página Inicial</title>
    <link rel="icon" type="image/png" href="{% static 'admin/img/box.png' %}">
    {% bootstrap_css %} {% bootstrap_javascript %} 
</head>
<body>
    <main>
    <div class="container d-flex flex-column justify-content-top align-items-center vh-100 text-center">
        <h1 >Bem-vindo a Página Inicial!</h1>
        <p>Inicie o gerencionamento de estoque!</p>
        <a href="{% url 'login' %}" class="btn btn-primary">Ir para a Lista de Produtos</a>
    </div>

    <hr class="featurette-divider">      
    <footer class="container-fluid bg-light text-center py-3 mt-auto">
        <hr class="featurette-divider">
        <div class="container">
            <p class="mb-1">
                &copy; Desenvolvido pelos alunos Felipe e Gabriel &middot;
            </p>
            <p><a href="#" class="btn btn-link">Voltar ao topo</a></p>
        </div>
    </footer>
    <main>  
    
</body>
</html>

app/templates/lista_estoque.html
{% load static %}
{% load django_bootstrap5 %}
<!DOCTYPE html>

<html lang="pt-br">
  <head>
    <link rel="stylesheet" href="{% static 'admin/css/estilo.css' %}">
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Listagem de Produtos</title>
    <link rel="icon" type="image/png" href="{% static 'admin/img/box.png' %}">
    <style type="text/css">
      html {
        margin: 2%;
      }
    </style>
    {% bootstrap_css %} {% bootstrap_javascript %}
  </head>
  <body class="body_principal" >
    <div class="container mt-5">
      <h1 class="text-center fw-bold mb-4">📦 Listagem de Produtos</h1>
  
      <div class="table-responsive">
          <table class="table table-hover table-bordered align-middle text-center">
              <thead class="table-dark">
                  <tr>
                      <th> Nome do Produto</th>
                      <th> Ações</th>
                  </tr>
              </thead>
              <tbody>
                  {% for estoque in object_list %}
                  <tr>
                      <td class="fw-semibold">{{ estoque.produto }}</td>
                      <td>
                          <a href="{% url 'listar_produto' pk=estoque.id %}" class="btn btn-info btn-sm">
                              <i class="fas fa-eye"></i> Exibir
                          </a>
                          <a href="{% url 'editar_produto' pk=estoque.id %}" class="btn btn-warning btn-sm">
                              <i class="fas fa-edit"></i> Editar
                          </a>
                          <a href="{% url 'remover_produto' pk=estoque.id %}" class="btn btn-danger btn-sm">
                              <i class="fas fa-trash-alt"></i> Remover
                          </a>
                      </td>
                  </tr>
                  {% endfor %}
              </tbody>
          </table>
      </div>
  </div>
    <a href="{% url 'form_estoque' %}" class="btn btn-primary"
      >Cadastrar um novo produto</a>
      <hr class="featurette-divider">      
    <footer class="rodape">
        <hr class="featurette-divider">
        <div class="container">
            <p class="mb-1">
              &copy; Desenvolvido pelos alunos Felipe e Gabriel &middot;
            </p>
            <p><a href="#" class="btn btn-link">Voltar ao topo</a></p>
        </div>
    </footer>
  </body>
</html>

app/templates/lista_produto.html
{% load static %}
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <link rel="stylesheet" href="{% static 'admin/css/estilo.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Listagem de Produto</title>
    <link rel="icon" type="image/png" href="{% static 'admin/img/box.png' %}">
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body class="body_principal conteudo_principal">
    <div class="container mt-5">
        <h2 class="text-center fw-bold  mb-4"> Produto</h2>

        <div class="card shadow-sm border-0">
            <div class="card-body">
                <form>
                    <div class="mb-3">
                        <label for="fproduto" class="form-label fw-bold">Nome:</label>
                        <input type="text" id="fproduto" name="fproduto" class="form-control" 
                               value="{{ fun.produto }}" readonly>
                    </div>

                    <div class="mb-3">
                        <label for="data_compra" class="form-label fw-bold">Data de Compra:</label>
                        <input type="date" id="data_compra" name="data_compra" class="form-control" 
                               value="{{ fun.data_compra|date:'Y-m-d' }}" readonly>
                    </div>

                    <div class="mb-3">
                        <label for="data_vencimento" class="form-label fw-bold">Data de Vencimento:</label>
                        <input type="date" id="data_vencimento" name="data_vencimento" class="form-control" 
                               value="{{ object.data_vencimento|date:'Y-m-d' }}" readonly>
                    </div>

                    <div class="mb-3">
                        <label for="quantidade" class="form-label fw-bold">Quantidade:</label>
                        <input type="text" id="quantidade" name="quantidade" class="form-control" 
                               value="{{ fun.quantidade }}" readonly>
                    </div>
                </form>
            </div>
        </div>

        <div class="text-center mt-4">
            <button type="button"class="btn btn-info btn-sm" onClick="history.go(-1)">
                 Voltar
            </button>
        </div>
    </div>

    <hr class="featurette-divider">      
    <footer class="rodape">
        <hr class="featurette-divider">
        <div class="container">
            <p class="mb-1">
                &copy; Desenvolvido pelos alunos Felipe e Gabriel &middot;
            </p>
        </div>
    </footer>
</body>
</html>

app/templates/login.html
{% load static %}
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'admin/css/estilo.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="icon" type="image/png" href="{% static 'admin/img/box.png' %}">
</head>
<body class="body_principal">
    <div class="container mt-5" >
        <h2 class="text-center fw-bold mb-4">Login</h2>

        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endfor %}
        {% endif %}

        <form method="POST"  class="mx-auto p-4 border rounded shadow fw-bold mb-4 bg-light text-dark" style="max-width: 400px;">
            {% csrf_token %}
            {{ form.as_p }}  

            <button type="submit" class="btn btn-primary w-100">Entrar</button>
        </form>       
    </div>
    <footer class="rodape">
        <hr class="featurette-divider">
        <div class="container">
            <p class="mb-1">
                &copy; Desenvolvido pelos alunos Felipe e Gabriel &middot;
            </p>
            <p><a href="#" class="btn btn-link">Voltar ao topo</a></p>
        </div>
    </footer>
</body>
</html>

app/templates/remover_produto.html
{% load static %}
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <link rel="stylesheet" href="{% static 'admin/css/estilo.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Remover Produto</title>
    <link rel="icon" type="image/png" href="{% static 'admin/img/box.png' %}">
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body class="body_principal conteudo_principal">
    <div class="container mt-5">
        <h2 class="text-center fw-bold mb-4"> Remover Produto?</h2>

        <div class="card shadow-sm border-0">
            <div class="card-body">
                <form>
                    <div class="mb-3">
                        <label class="form-label fw-bold">Nome:</label>
                        <input type="text" class="form-control" value="{{ object.produto }}" readonly>
                    </div>

                    <div class="mb-3">
                        <label class="form-label fw-bold">Data de Compra:</label>
                        <input type="date" class="form-control" value="{{ object.data_compra|date:'Y-m-d' }}" readonly>
                    </div>

                    <div class="mb-3">
                        <label class="form-label fw-bold">Data de Vencimento:</label>
                        <input type="date" class="form-control" value="{{ object.data_vencimento|date:'Y-m-d' }}" readonly>
                    </div>

                    <div class="mb-3">
                        <label class="form-label fw-bold">Quantidade:</label>
                        <input type="text" class="form-control" value="{{ object.quantidade }}" readonly>
                    </div>
                </form>
            </div>
        </div>

        <div class="text-center mt-4">
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger btn-sm px-4"> Sim, remover</button>
                <a href="{% url 'lista_estoque' %}" class="btn btn-info btn-sm px-4"> Cancelar</a>
            </form>
        </div>
    </div>

    <hr class="featurette-divider">      
    <footer class="rodape">
        <hr class="featurette-divider">
        <div class="container">
            <p class="mb-1">
                &copy; Desenvolvido pelos alunos Felipe e Gabriel &middot;
            </p>
        </div>
    </footer>
</body>
</html>